# Generated by Django 2.2 on 2019-07-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190303_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sumary',
            new_name='summary',
        ),
    ]
