# Generated by Django 2.2.4 on 2019-08-18 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190723_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 10, 54, 55, 868001), verbose_name='date published'),
        ),
    ]
